# Generated by Django 3.2 on 2021-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='minutesname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
